Added support for sq v2
num-codex/codex-feasibility-backend pull request #66
Opened 2021-12-03 13:41 UTC by geloro94

2021-12-06 13:09 UTC, DiCanio requested changes
Thanks for the additions. I left some comments that can be discussed if necessary.

**Regarding the test cases:**
As stated within one of the review comments, I'm aware that we are not testing the actual builder classes. Instead, it is some kind of serialization / deserialization test. To test the actual builder we need real integration tests against a compatible Flare version.
I'm working on a solution for this in #65. If you don't mind, then we can adjust these test cases in said issue.
However, we can also try to implement all the necessary changes for this right here.

Looking forward to opinions.

2021-12-06 15:15 UTC, geloro94 commented on src/main/java/de/numcodex/feasibility_gui_backend/model/ui/Criterion.java
> +  private ArrayList<TermCode> termCodes;
Won't do that unless we change its definition in sqv2. termCode in my opinion is the preferred name here, to indicate the termCodes are synonyms and not a list of different termCodes.

2021-12-07 10:49 UTC, DiCanio requested changes
Just 2 potential little typos.

2021-12-07 10:49 UTC, DiCanio commented on src/test/java/de/numcodex/feasibility_gui_backend/model/StructuredQueryV2ParserTest.java
> +    assert (jsonString.contains("attributeCode"));
```suggestion
    assert (jsonString.contains("attributeFilters"));
```

Could be a potential typo, otherwise this line would be a duplicate.

2021-12-07 10:49 UTC, DiCanio commented on src/test/java/de/numcodex/feasibility_gui_backend/service/query_builder/FhirQueryBuilderTest.java
> +    assert (jsonString.contains("attributeCode"));
Same potential typo.

2021-12-07 10:49 UTC, DiCanio commented on src/main/java/de/numcodex/feasibility_gui_backend/model/ui/Criterion.java
> +  private ArrayList<TermCode> termCodes;
Ok, didn't know about that.

Maybe we can document this somewhere (definition readme; code comment etc.).
Something along the lines of `Collection of synonymous term codes which consequently describe the same thing. Thus, serialized as a singular termCode key.`

2021-12-10 10:07 UTC, merged